version: "3.8"

services:
  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.cpu.server
    image: marker-api-cpu-image
    command: celery -A marker_api.celery_worker.celery_app worker --pool=solo -n worker_primary --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
    restart: unless-stopped

  app:
    container_name: marker-api-cpu
    image: marker-api-cpu-image 
    command: python distributed_server.py --host 0.0.0.0 --port 8092
    environment:
      - ENV=production
    ports:
      - "8092:8092"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery_worker
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  flower:
    container_name: flower_cpu
    image: marker-api-cpu-image
    command: celery -A marker_api.celery_worker.celery_app flower --port=5555
    ports:
      - 5556:5555
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - app
      - redis
      - celery_worker
    restart: unless-stopped
